
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 3
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Helsinki
    commit-message:
      prefix: ci
      include: scope
    assignees:
      - jtakalai
    labels:
      - github-actions
      - dependencies
  - package-ecosystem: docker
    directory: /
    open-pull-requests-limit: 3
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Helsinki
    commit-message:
      prefix: build
      include: scope
    assignees:
      - jtakalai
    labels:
      - javascript
      - dependencies
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 3
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Helsinki
    commit-message:
      prefix: test
      include: scope
    assignees:
      - jtakalai
    labels:
      - javascript
      - dependencies

