language: node_js
node_js:
  - "10.19.0"
before_install:
  - "npm i -g npm@6.13.4"
branches:
  only:
    - master
    - next
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
jobs:
  include:
    - stage: lint & unit-test
      script:
        - "npm run lint"
        - "npm run unit-test"
    - stage: integration / end-to-end test
      script:
        - sudo /etc/init.d/mysql stop
        - sudo ifconfig docker0 10.200.10.1/24
        - git clone https://github.com/streamr-dev/streamr-docker-dev.git
        - streamr-docker-dev/streamr-docker-dev/bin.sh start --wait
        - docker ps
# print system usage stats
        - uname -a
        - top -n1
        - free -h
        - df -h
        - npm run build
        - npm run integration-test
      env:
        - DEBUG=*
        - TEST_TIMEOUT=600000
