name: Continuous Integration

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      # - name: Build Solidity contracts using makefile
      #   working-directory: packages/contracts
      #   run: |
      #      make build
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --no-audit
      - name: Run lint
        run: npm run lint --workspaces --if-present
      - name: Build and unit test
        run: |
          npm run build
          npm run test
      - name: Start Streamr Docker Stack
        uses: streamr-dev/streamr-docker-dev-action@v1.0.0
        with:
          services-to-start: 'parity-sidechain-node0 parity-node0 bridge core-api nginx'
      - name: Integration Test
        env:
          TEST_TIMEOUT: '600000'
        run: npm run integration-test --workspaces --if-present
