---
name: Dependency
on:
  - pull_request

permissions:
  contents: read

jobs:
  dependency-review:
    name: Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Dependency Review
        uses: actions/dependency-review-action@v2
